/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kason_zhang_myndk_MyNDK */

#ifndef _Included_com_kason_zhang_myndk_MyNDK
#define _Included_com_kason_zhang_myndk_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kason_zhang_myndk_MyNDK
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kason_1zhang_myndk_MyNDK_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
